### ISSUE TITLE
关于葫芦侠的评论机制

### ISSUE THREAD

**Issue by yehuzhucha** [xiguac/HuluxiaTools#1]
大佬好，项目经测试可用，但有一个问题就是葫芦侠会监测重复评论，无法实现自动顶贴，请问有什么好的解决办法吗

**Comment by xiguac** [comment]
可以在评论末尾添加上表情符号，或者使用uniqid()生成随机id，附加在评论文字后面

**Comment by yehuzhucha** [comment]
谢谢，已达到预期效果
