### ISSUE TITLE
执行好了什么也不显示吗

### ISSUE THREAD

**Issue by Skin0111** [xiguac/HuluxiaTools#3]
签到那个脚本执行了什么也不显示正常吗，账号被顶了
![wx_camera_1659482509445](https://user-images.githubusercontent.com/102968183/182492754-c99ba08a-d878-497c-89e2-3bdaffeae588.jpg)

**Comment by xiguac** [comment]
![image](https://user-images.githubusercontent.com/58496501/182501183-fc2d2631-a5dc-445e-b955-0bc5a0ca1261.png)
正常执行完是这样的，一般执行一次需要10秒左右（网页加载的时候不要重复刷新）。
如果网页什么都没有显示可以多刷新几次
你也可以打开葫芦侠手机软件查看是否签到成功
